// Postbuild step (kickoff Prompt 2 item 7 / Prompt 4): scans the built
// HTML for `[TODO: KEY]` markers (src/lib/placeholders.ts substitute())
// and writes docs/TODO.md grouped by page. Scanning the actual build
// output — rather than tracking substitutions in memory during the
// build — means this always matches exactly what shipped, regardless of
// which module rendered the marker (layout body, footer NAP, meta tags).
import fs from "node:fs";
import path from "node:path";

const distDir = path.resolve(process.cwd(), "dist");
const outPath = path.resolve(process.cwd(), "docs/TODO.md");
const TODO_RE = /\[TODO: ([A-Za-z0-9_.-]+)\]/g;

function walkHtmlFiles(dir) {
  const out = [];
  for (const entry of fs.readdirSync(dir, { withFileTypes: true })) {
    const full = path.join(dir, entry.name);
    if (entry.isDirectory()) out.push(...walkHtmlFiles(full));
    else if (entry.name === "index.html") out.push(full);
  }
  return out;
}

if (!fs.existsSync(distDir)) {
  console.error("docs/TODO.md: dist/ not found — run `astro build` first.");
  process.exit(1);
}

const perPage = new Map(); // url -> Set<key>

for (const file of walkHtmlFiles(distDir)) {
  const html = fs.readFileSync(file, "utf-8");
  const keys = new Set([...html.matchAll(TODO_RE)].map((m) => m[1]));
  if (keys.size === 0) continue;
  const rel = path
    .relative(distDir, path.dirname(file))
    .split(path.sep)
    .filter(Boolean)
    .join("/");
  const url = rel === "" ? "/" : `/${rel}/`;
  perPage.set(url, keys);
}

const lines = [
  "# TODO",
  "",
  "Auto-generated by `npm run build` (scripts/write-todo.mjs), by scanning the built HTML for `[TODO: KEY]` markers. Every page below rendered at least one unresolved placeholder. Fill the value in docs/placeholders.json and rebuild to clear an entry.",
  "",
];

const sortedUrls = [...perPage.keys()].sort();
if (sortedUrls.length === 0) {
  lines.push("None — every placeholder used on a built page is resolved.");
} else {
  for (const url of sortedUrls) {
    lines.push(`## ${url}`);
    for (const key of [...perPage.get(url)].sort()) {
      lines.push(`- [ ] \`{{${key}}}\``);
    }
    lines.push("");
  }
}

fs.writeFileSync(outPath, lines.join("\n"));
console.log(`docs/TODO.md written: ${sortedUrls.length} page(s) with unresolved placeholders.`);
